version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo "Build started"
      # You can add additional build steps here
artifacts:
  files: '**/*'
  name: website
