AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: '*'
      Roles:
        - !Ref AWSCodePipelineServiceRole-us-east-1-sami-test-pipeline
