AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: samiPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: '*'
      Roles:
        - !Ref AWSCodePipelineServiceRole

  AWSCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCodePipelineServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
